services:
  frontend:
    image: jakmad/frontend_madej.art:latest
    command: npm run watch
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./images:/frontend/public/images

  backend:
    image: jakmad/api_madej.art:latest
    command: npm start
    ports:
      - "3001:3001"
    networks:
      - app-network
    volumes:
      - ./images:/backend/src/images
      - ./database:/backend/src/database

networks:
  app-network:
    driver: bridge
